### ISSUE TITLE
Potential business opportunities?

### ISSUE THREAD

**Issue by arjamizo** [michcioperz/nnnnnnaas#1]
What are potential business opportunities of this software?

**Comment by Michcioperz** [comment]
You can satisfy weeaboos' dank desires. Otherwise there is no effect on business aside from bandwidth.

**Comment by asiekierka** [comment]
@arjamizo The Shinonome Laboratories are an academic organization and, as such, do not seek immediate business benefits beyond the sale of "Biscuit Boy"-type simplified robot designs. I suppose you could file this under "marketing expenses" for brand recognition.

**Comment by Michcioperz** [comment]
@arjamizo I take it that our answers were sufficient for you, if you don't run into any more questions within a day I'll go ahead and close the issue.
